#pragma once

// to save firmware space: 
#define BOOTMAGIC_ENABLE = yes
#define BOOTMAGIC_KEY_SALT KC_V
#define BOOTMAGIC_KEY_EEPROM_CLEAR KC_Q
/* #undef RGBLIGHT_ANIMATIONS */
/* #undef RGBLIGHT_EFFECT_BREATHING */
/* #undef RGBLIGHT_EFFECT_RAINBOW_MOOD */
/* #undef RGBLIGHT_EFFECT_RAINBOW_SWIRL */
/* #undef RGBLIGHT_EFFECT_SNAKE */
/* #undef RGBLIGHT_EFFECT_KNIGHT */
/* #undef RGBLIGHT_EFFECT_CHRISTMAS */
/* #undef RGBLIGHT_EFFECT_STATIC_GRADIENT */
/* #undef RGBLIGHT_EFFECT_RGB_TEST */
/* #undef RGBLIGHT_EFFECT_ALTERNATING */
/* #undef RGBLIGHT_EFFECT_TWINKLE */
/* #define BLUETOOTH_ENABLE = no */
/* #define AUDIO_ENABLE = no */
